# Generated by Django 6.1.1 on 2026-09-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumnus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("graduation_year", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "alumnus",
                "verbose_name_plural": "alumni",
                "ordering": ["-graduation_year", "last_name", "first_name"],
            },
        ),
    ]
