# Generated by Django 6.1.1 on 2026-10-03 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alumni", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BacSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "period",
                    models.CharField(
                        blank=True,
                        help_text='E.g. "since 2021", "1995-2020", "before 1995".',
                        max_length=100,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order (e.g. most recent series first).",
                    ),
                ),
            ],
            options={
                "verbose_name": "bac series",
                "verbose_name_plural": "bac series",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AlterField(
            model_name="alumnus",
            name="graduation_year",
            field=models.PositiveIntegerField(verbose_name="graduation year"),
        ),
        migrations.AddField(
            model_name="alumnus",
            name="bac_series",
            field=models.ForeignKey(
                blank=True,
                help_text="Temporarily optional: no reference data is seeded yet.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="alumni",
                to="alumni.bacseries",
            ),
        ),
    ]
