# Generated by Django 6.1.1 on 2026-10-03 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alumni", "0002_bacseries_alter_alumnus_graduation_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumnus",
            name="current_focus",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Short, free-form summary of what they currently study or do, e.g. "Software engineer at X, focused on distributed systems".',
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="StudyStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "program",
                    models.CharField(
                        help_text='E.g. "CPGE MPSI", "Erasmus semester", "Engineering degree".',
                        max_length=200,
                    ),
                ),
                ("institution", models.CharField(blank=True, max_length=200)),
                ("start_year", models.PositiveSmallIntegerField()),
                (
                    "end_year",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Leave empty if still ongoing.", null=True
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Manual ordering for stages sharing the same start year.",
                    ),
                ),
                (
                    "alumnus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_stages",
                        to="alumni.alumnus",
                    ),
                ),
            ],
            options={
                "verbose_name": "study stage",
                "verbose_name_plural": "study stages",
                "ordering": ["order", "start_year"],
            },
        ),
    ]
