repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.9
    hooks:
      - id: ruff
        args: [--fix,
          "--extend-select=E,F,I,DJ",
          --exclude=*/migrations/*,
          --line-length=120,
          --ignore=RUF012
        ]
      - id: ruff-format

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.1
    hooks:
      - id: gitleaks